# Generated by Django 4.2.17 on 2025-03-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
