# Generated by Django 4.2.21 on 2025-06-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_order_date_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
