# Generated by Django 4.2.21 on 2025-06-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_order_tracking_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('cancellation_requested', 'Cancellation Requested')], default='pending', max_length=30),
        ),
    ]
