# Generated by Django 4.2.17 on 2025-05-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_items_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
