# Generated by Django 4.2.21 on 2025-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_sizevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='has_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
