# Generated by Django 4.2.21 on 2025-06-04 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_items_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='has_sizes',
        ),
    ]
