# Generated by Django 5.0.6 on 2024-07-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('items', '0003_alter_items_options_alter_items_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(through='cart.CartItem', to='items.items'),
        ),
    ]
