# Generated by Django 4.2.17 on 2025-05-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_sizevariant'),
        ('cart', '0003_remove_cart_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.sizevariant'),
        ),
    ]
