# Generated by Django 4.2.17 on 2025-05-21 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_sizevariant'),
        ('cart', '0004_cartitem_size_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('added_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item', 'size_variant')},
        ),
    ]
