# Generated by Django 4.2.21 on 2025-06-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('notifications', '0002_rename_message_notification_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conversation.conversation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_shipped', 'Order Shipped'), ('order_canceled', 'Order Canceled'), ('tracking_update', 'Tracking Number Updated'), ('general', 'General Notification'), ('order_placed', 'Order Placed'), ('new_message', 'New Message')], default='general', max_length=50),
        ),
    ]
